# Generated by Django 4.2.27 on 2025-12-10 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(8)])),
                ('city', models.CharField(blank=True, max_length=50)),
                ('web_server', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('sign_ins', models.CharField(max_length=100)),
            ],
        ),
    ]
